<div class="modal fade" id="modalCadastroRapido" tabindex="-1" role="dialog" aria-hidden="true">
 <div class="modal-dialog modal-lg" role="document"><div class="modal-content"><form id="quick_form" novalidate enctype="multipart/form-data">
  @csrf
  <div class="modal-header bg-primary text-white"><h5 class="modal-title" id="quick_title">Cadastro rápido</h5><button type="button" class="close text-white" data-dismiss="modal" aria-label="Fechar">&times;</button></div>
  <div class="modal-body"><div id="quick_alert" class="alert alert-danger d-none"></div><input type="hidden" id="quick_type"><input type="hidden" id="quick_motorista_flag" name="motorista" value="0">
   <div class="quick-person row">
    <div class="form-group col-md-5"><label>Razão social / Nome *</label><input id="quick_razao_social" name="razao_social" class="form-control"><div class="invalid-feedback"></div></div>
    <div class="form-group col-md-4"><label>CPF/CNPJ</label><div class="input-group"><input id="quick_cpf_cnpj" name="cpf_cnpj" class="form-control" inputmode="numeric"><div class="input-group-append"><button id="quick_consultar_cnpj" class="btn btn-outline-primary" type="button" title="Consultar CNPJ" aria-label="Consultar CNPJ"><i class="fa fa-search"></i></button></div></div><div class="invalid-feedback"></div></div>
    <div class="form-group col-md-3"><label>Nome fantasia</label><input id="quick_nome_fantasia" name="nome_fantasia" class="form-control"><div class="invalid-feedback"></div></div>
    <div class="form-group col-md-4"><label>Chave PIX *</label><input id="quick_pix" name="pix" class="form-control" maxlength="40"><div class="invalid-feedback"></div></div><div class="form-group col-md-4"><label>Telefone</label><input name="telefone" class="form-control"><div class="invalid-feedback"></div></div><div class="form-group col-md-4"><label>Celular</label><input name="celular" class="form-control"></div>
    <div class="form-group col-md-4"><label>CEP</label><div class="input-group"><input id="quick_pessoa_cep" name="cep" class="form-control" inputmode="numeric"><div class="input-group-append"><button class="btn btn-outline-primary quick-buscar-cep" type="button" title="Buscar endereço pelo CEP" aria-label="Buscar endereço pelo CEP"><i class="fa fa-search"></i></button></div></div><div class="invalid-feedback"></div></div>
    <div class="form-group col-md-6"><label>Rua</label><input name="rua" class="form-control"><div class="invalid-feedback"></div></div><div class="form-group col-md-2"><label>Número</label><input name="numero" class="form-control"><div class="invalid-feedback"></div></div><div class="form-group col-md-4"><label>Bairro</label><input name="bairro" class="form-control"><div class="invalid-feedback"></div></div>
    <div class="form-group col-md-8"><label>Cidade</label><select id="quick_cidade_id" name="cidade_id" class="form-control" style="width:100%;"><option value="">Selecione</option>@foreach(\App\Models\Cidade::orderBy('nome')->get() as $cidade)<option value="{{ $cidade->id }}" data-nome="{{ \Illuminate\Support\Str::upper($cidade->nome) }}" data-uf="{{ \Illuminate\Support\Str::upper($cidade->uf) }}" {{ (($cidadePadraoCadastroRapido->id ?? null) == $cidade->id) ? 'selected' : '' }}>{{ $cidade->info }}</option>@endforeach</select><div class="invalid-feedback"></div></div>
   </div>
   <div class="quick-vehicle row d-none">
    @foreach(['placa'=>'Placa *','uf'=>'UF','marca'=>'Marca','modelo'=>'Modelo','cor'=>'Cor','tipo'=>'Tipo','tara'=>'Tara','capacidade'=>'Capacidade','combustivel'=>'Combustível','proprietario_nome'=>'Proprietário','proprietario_documento'=>'CPF/CNPJ proprietário','proprietario_ie'=>'IE/RG proprietário','proprietario_uf'=>'UF proprietário'] as $field=>$label)<div class="form-group col-md-4"><label>{{ $label }}</label><input name="{{ $field }}" class="form-control"><div class="invalid-feedback"></div></div>@endforeach
    <div class="form-group col-md-4"><label>Tipo proprietário *</label><select id="quick_proprietario_tp" name="proprietario_tp" class="form-control" style="width:100%;"><option value="0">Próprio</option><option value="1">Terceiro</option></select></div><div class="form-group col-md-4"><label>Motorista (opcional)</label><select id="quick_motorista_id" name="motorista_id" class="form-control" style="width:100%;"></select></div>
   </div>
   <div class="quick-employee row d-none">
    <div class="form-group col-md-6"><label>Nome *</label><input name="nome" class="form-control"><div class="invalid-feedback"></div></div><div class="form-group col-md-3"><label>CPF</label><input id="quick_funcionario_cpf" name="cpf" class="form-control" inputmode="numeric"><div class="invalid-feedback"></div></div><div class="form-group col-md-3"><label>RG</label><input name="rg" class="form-control"><div class="invalid-feedback"></div></div>
    <div class="form-group col-md-4"><label>CEP</label><div class="input-group"><input id="quick_funcionario_cep" name="cep" class="form-control" inputmode="numeric"><div class="input-group-append"><button class="btn btn-outline-primary quick-buscar-cep" type="button" title="Buscar endereço pelo CEP" aria-label="Buscar endereço pelo CEP"><i class="fa fa-search"></i></button></div></div></div>
    <div class="form-group col-md-6"><label>Rua</label><input name="rua" class="form-control"><div class="invalid-feedback"></div></div><div class="form-group col-md-2"><label>Número</label><input name="numero" class="form-control"><div class="invalid-feedback"></div></div><div class="form-group col-md-4"><label>Bairro</label><input name="bairro" class="form-control"><div class="invalid-feedback"></div></div><div class="form-group col-md-6"><label>Telefone</label><input name="telefone" class="form-control"><div class="invalid-feedback"></div></div><div class="form-group col-md-6"><label>Celular</label><input name="celular" class="form-control"><div class="invalid-feedback"></div></div>
    <div class="quick-cnh form-group col-md-4"><label>CNH</label><input name="cnh" class="form-control"></div><div class="quick-cnh form-group col-md-3"><label>Categoria</label><select id="quick_categoria_cnh" name="categoria_cnh" class="form-control" style="width:100%;"><option value="">-</option>@foreach(['A','B','C','D','E'] as $c)<option>{{ $c }}</option>@endforeach</select></div><div class="quick-cnh form-group col-md-3"><label>Vencimento</label><input type="date" name="vencimento_cnh" class="form-control"></div>
   </div>
   <div class="quick-image form-group mb-0 d-none"><label for="quick_imagem">Foto (opcional)</label><input id="quick_imagem" type="file" name="imagem" class="form-control-file" accept="image/jpeg,image/png,image/webp"><small class="form-text text-muted">JPG, PNG ou WEBP, até 2 MB.</small><div class="invalid-feedback"></div></div>
  </div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button><button id="quick_submit" class="btn btn-primary" type="submit">Salvar cadastro</button></div>
 </form></div></div>
</div>
